### ISSUE TITLE
Legacy material support

### ISSUE THREAD

**Issue by MelnCat** [TheBozzz34/UPnP#3]
Currently, this plugin lacks an `api-version` in the plugin.yml, causing it to be a legacy plugin. This causes the server to initialize legacy material support when the plugin is present, reducing performance, when the plugin does not require legacy material support.

**Comment by TheBozzz34** [comment]
Fixing in version 1.7.1

**Comment by TheBozzz34** [comment]
Update posted to Modrinth and Spigot.
